### PR TITLE
Changes to allow kubernetes input to use host IP instead of hostname

### PR DESCRIPTION
**Pull request by mkjpryor-stfc**
On systems where hostnames are resolved on each node using `/etc/hosts` rather than DNS (primarily test clusters), the hostname is not resolvable inside containers. This breaks the `telegraf-ds` integration with `kubelet`, which assumes the hostname is resolvable inside the container.

This patch injects the `HOSTIP` into the `telegraf-ds` pods as well as `HOSTNAME`, and uses it in the `kubelet` address in the default `values.yaml`. This means that the `kubelet` integration will work out of the box on all clusters, including those configured using `/etc/hosts`.

Additionally, the patch includes checksums of secrets/configmaps in the annotations of deployments and daemonsets. This means that the deployment/daemonset will get rolled if the configuration is updated.

### CODE REVIEW

**Comment by jackzampolin** [comment]
@mkjpryor-stfc Thanks for the PR. I also like the addition of the checksums to make changes restart the pods. I've pulled this down and it looks good. We should merge this!

**Comment by mkjpryor-stfc** [comment]
@jackzampolin: Cool! Let me know if you need anything else from me.

**Comment by jackzampolin** [comment]
@mkjpryor-stfc I am no longer the maintainer on this repo so I can't merge your stuff!

**Comment by mkjpryor-stfc** [comment]
@jackzampolin: Fair enough - I just assumed you were! Who is then?

**Comment by timhallinflux** [comment]
@mkjpryor-stfc Thank you! It's me...and some others.  
@jackzampolin -- Thanks for the review.

**Pull request merged**
