### PR TITLE
[Telegraf] Allow full use of duplicate input/ouputs in telegraf configuration 

### PR DESCRIPTION
**Pull request by amoskyler**
* Porting changes from https://github.com/helm/charts/pull/4170 to Upstream *

*What this PR does / why we need it:*
This change converts the inputs and outputs fields from an object with keys associated to configs, to an array of objects which contain keys associated to objects.

Before:
```
config:
  outputs:
     influxdb:
      ...config...
```
After:
```
config:
  outputs:
    - influxdb:
       ...config...
```

Telegraf supports multiples of same type input and output configurations. In the current chart implementation, each input and output is configured with keys in the objects inputs and outputs respectively. YAML overrides the first key in the object however, and therefore the templating process from YAMl to TOML drops valid TOML configurations, which incorrectly limits valid configurations.

### CODE REVIEW

**Comment by amoskyler** [comment]
@timhallinflux CLA has been signed!

**Comment by amoskyler** [comment]
@timhallinflux makes sense regarding Chart version. My reasoning behind changing the version is this change will in fact break previous chart value configurations. But, as it is pinned to the GA of Telegraf I will modify.

**Comment by amoskyler** [comment]
@timhallinflux Any chance we can get this merged in? Or of course if you have any further issues/comments I am willing to address them.

**Comment by amoskyler** [comment]
I intended that to be an example of using duplicate configuration keys.

**Comment by timhallinflux** [comment]
also in telegraf-s/templates/NOTES.txt -- the -s is for the standalone Telegraf and the -ds is the daemonset.  It looks like you made changes to the telegraf-s/templates/NOTES.txt which reference the daemonset --- but I don't think that's appropriate in this case.

**Comment by dtshepherd** [comment]
@amoskyler @timhallinflux Any updates on getting this merged in?  I just came across the limitation and need to define two outputs to two different influxdbs with different configs (database names, password vs ssl, etc).  This PR also makes it possible to define other config keys such as `ssl_key`, `ssl_cert`, and `ssl_ca`.

I'm trying to avoid forking this repo and maintaining my own chart repo if possible :)

**Comment by timhallinflux** [comment]
fixes #11

**Pull request merged**
